services:
  - type: web
    name: free-sewaa-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://swarnimkarki60_db_user:qcljLKasZ49L08Mq@free-sewaa.qtyv3z2.mongodb.net/?appName=Free-Sewaa
        sync: false
      - key: NODE_ENV
        value: production